### ISSUE TITLE
set images array would be realy nice

### ISSUE THREAD

**Issue by NMathar** [deulos/vue-flux#10]
Sorry its me again :cry: 

My Image array changes from time to time dynamical without a reload is it possible ti implement a set image or update image array function?

**Comment by NMathar** [comment]
ok works with 
````javascript
this.$refs.slider.preloadImages(this.fluxImages);
````

**Comment by deulos** [comment]
No problem Nico, I'm glad to help when I have some time to spare.

You found it alone, nice!
