### ISSUE TITLE
How do I use this great app with nuxtjs

### ISSUE THREAD

**Issue by folamy** [deulos/vue-flux#11]
Please is there a way to use VueFlux with nuxtjs
I am getting  nuxt error :  window/document undefined?

**Comment by deulos** [comment]
Please, share a repo so I can test it, shouldn't give you any problem on SSR

**Comment by deulos** [comment]
I don't see anything wrong in that piece of code... If you really want me to help you better send a repo so I can debug the problem...

**Comment by folamy** [comment]
Please just help me.... my repo is a very huge project and i need to get this fixed

**Comment by deulos** [comment]
Cant you just create a sample repo?

**Comment by deulos** [comment]
Hello, testing it in new nuxt project this is as far as I got without experience, hope it helps you...

> nuxt.config.js

``` javascript
  plugins: [{
    src: '~/node_modules/vue-flux', ssr: false
  }],
  build: {
    vendor : ['vue-flux'],
```

> index.vue

``` javascript
let VueFlux;
let Transitions;

if (process.browser) {
   const VF = require('vue-flux');
   VueFlux = VF.VueFlux;
   Transitions = VF.Transitions;
}

export default {
   components: {
      VueFlux
   },

   data: () => ({
      fluxOptions: {
         autoplay: false
      },
      fluxImages: [
         'https://source.unsplash.com/random',
         'https://source.unsplash.com/random',
         'https://source.unsplash.com/random'
      ],
      fluxTransitions: Transitions
   })
}
```

It seems to work because it doesn't return the document undefined error but the browser reports this error:

> The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside p, or missing tbody. Bailing hydration and performing full client-side render.

**Comment by folamy** [comment]
okay...thanks i will try this and get back to you

**Comment by deulos** [comment]
Glad to hear that.

Regards
