### ISSUE TITLE
components are not displaying

### ISSUE THREAD

**Issue by ondrejlohnisky** [deulos/vue-flux#16]
FluxCaption, FluxControls, FluxIndex, FluxPagination are not working. Am i using it correctly?

[component.txt.txt](https://github.com/deulos/vue-flux/files/2412760/component.txt.txt)

**Comment by ondrejlohnisky** [comment]
`import { VueFlux, FluxCaption, FluxControls, FluxIndex, FluxPagination, Transitions, FluxParallax } from 'vue-flux';
export default {
    data:()=>{
        return{
            images:['https://amp.businessinsider.com/images/59bdf58b38d20d41188b6d2d-750-563.jpg','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD_QNzGGCCIzsUCC92NIBRbgWrD0bjcBTUxHGR1yKB29b0Lhb6','https://usatthebiglead.files.wordpress.com/2016/07/gettyimages-523605168.jpg'],
            fluxOptions: {
                autoplay: true,
				bindKeys: true,
				fullscreen: false,
				infinite: true,
				delay: 5000,
				width: '500px',
				height: '500px'
            },
            fluxTransitions: {
                transitionSlide: Transitions.transitionSlide
            }
        }
    },
    components:{
        VueFlux,
        FluxCaption,
        FluxControls,
        FluxIndex,
        FluxPagination,
        FluxParallax
    }
}`

**Comment by deulos** [comment]
Looks like you are using them properly...

Any console error?

**Comment by ondrejlohnisky** [comment]
No. I don’t get any error.

**Comment by KaiserY** [comment]
At certain situation, the slider props of the slot components is undefined. Maybe some kind of race condition ?

**Comment by BorysTyminski** [comment]
@ondrejlohnisky do you overwrite some vueFlux styles? It uses some styles to display buttons

**Comment by ondrejlohnisky** [comment]
Okay, i am using VueJs integrated with Laravel. But it should be the same, don’t?
Yeah i think that the $refs.slider is undefined so the component dont renender. But why...
I will upload my whole project later today.

**Comment by deulos** [comment]
$refs.slider is undefined until the template is rendered, then the component is displayed.

Certainly using laravel must not be a problem.

You dont need to upload the whole project, just the piece that renders the component.

**Comment by ondrejlohnisky** [comment]
Here:
https://github.com/ondrejlohnisky/littleDemoRepository

**Comment by BorysTyminski** [comment]
> I found the problem, what I don't understand is why was not happenning before.

at my app i have 5 different sliders using always vue-flux and i was also encountering this issue that my flux component's didn't display but only in one of them so i just thought that I'm doing something wrong. That's werid that this issue occurs only occasionally.

**Comment by deulos** [comment]
It is just about rendering timing, so depending on the time to load sometimes references are loaded properly and other times not.

It was one of the request ofr the future Vue versions, to make $refs reactive but seems like Evan You refused it.

**Comment by deulos** [comment]
Not lucky right now finding a solution but at least I was able to reproduce the issue in the demo removing all but the slider :S

**Comment by deulos** [comment]
I tested different approaches, and the best I found was to load the component async, because the other option was to set a variable indicating when the parent component is mounted and setting an v-if in every slot, which makes me feel unconfortable.

So I will update the docs with the propper declaration in a few seconds :)

**Comment by deulos** [comment]
Solution explained in [Changelog](https://github.com/deulos/vue-flux/wiki/Changelog)

Let me know if you find an issue.

Thanks for your patience!

**Comment by deulos** [comment]
I am not convinced with this solution so after thinking about it in dreams XD I found simplier and less cryptic way, so I will create a new release this week.

Regards!

**Comment by deulos** [comment]
I update the slider and there is not need anymore to load flux components async nor to pass the slider as ref if they inside the vue-flux component!!

I will update the docs right now.

**Comment by ondrejlohnisky** [comment]
Thanks:) just update the docs
Godd job.
