### ISSUE TITLE
'infinite' option is ignored

### ISSUE THREAD

**Issue by mariusgen** [deulos/vue-flux#17]
I am having these options: autoplay - which is working fine, and infinite which seems to remain always 'true'.

`fluxOptions: {
    autoplay: false,
          infinite: false
      }`

**Comment by deulos** [comment]
Thank you, I will check it tomorrow

**Comment by mariusgen** [comment]
@deulos infinite prop is used only for autoplay? If I am at the end and I press Next, the slider is starting with the first slide. I thought it is used for this case too, to avoid to start over. Thanks

**Comment by deulos** [comment]
No, is just to stop it automatically when reaches the last.

I will try to explain it better in wiki.

Regards!
