### ISSUE TITLE
slider is not moveable on mobile device

### ISSUE THREAD

**Issue by BorysTyminski** [deulos/vue-flux#18]
As title says I'm not able to scroll page with finger when touching on slider.

**Comment by deulos** [comment]
Hello! That's an intended behaviour.

The control and index components are displayed on mouse over, but in touchable screens there is no mouse, so they have to work by gestures.

The problem is that if you try todo a gesture and don't stop the event propagation (dragging) you will lose the slider out of sight, that means, when you want to show next, previous, index and full screen. So yes dragging (scrolling) the page starting from inside slider is not possible.

If you have an idea on how to do it anohter way Im open :)

**Comment by BorysTyminski** [comment]
You can not leave it like that because when I use slider as background for first screen user is not able to move page to bottom. I would suggest to just use media queries to display control and index on smaller than 768px without using mouse over event. Also question - how to disable full screen mode after double click?

**Comment by BorysTyminski** [comment]
> you will lose the slider out of sight, that means, when you want to show next, previous, index and full screen

I understand gestures feature but I think that there should be optional flag to disable hiding and showing animation and make next, previous and button of index static. 

It's sometimes needed because not all user on mobile device will try to slide finger left or right they don't know that they can do it to change photo so sometimes I prefer to just always show buttons on slider for example when page is 100% vh and vw;

I see that the buttons nicely hide and show when mouseover but I think there should be a optional flag to change that to make them static without hiding and showing when needed. For example on mobile device I don't want them to hide and show. I can't think about someone that would

**Comment by deulos** [comment]
I'll create an option to disable gestures and maintain components button visible on touchable devices.

**Comment by deulos** [comment]
You can already disable full screen, there is an option for that.

**Comment by BorysTyminski** [comment]
Ah sorry I haven't notice

**Comment by deulos** [comment]
:)

**Comment by deulos** [comment]
Released, let me know if you find any issue.

Regards!

**Comment by BorysTyminski** [comment]
That's werid, when I switch to 5.1.0 I get error

> Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\Borys\Documents\TwoHouse\public\node_modules\vue-flux\dist\vue-flux.umd.min.js'

Although I see this file witihin vue-flux directory inside node_modules.
