### ISSUE TITLE
Using with nuxtjs

### ISSUE THREAD

**Issue by LeCongThang** [deulos/vue-flux#2]
Hi, i'm have a nuxtjs project and i want to using slider in my project. But when i follow guide, i got a problem that `Vue is not defined at \node_modules\vue-flux\dist\vue-flux.min.js`. Somebody had using with nuxtjs can help me? Thanks
In my `nuxt.config.js`
`build: {
    vendor: ['axios','vue-flux']
}`
And in my `index.vue` page
```<template>
  <section class="wrapper">
      <vue-flux
        :options="fluxOptions"
        :images="fluxImages"
        :transitions="fluxTransitions"
        ref="slider">
      </vue-flux>   
  </section>
</template>
<script>
import { VueFlux, Transitions } from "vue-flux";
export default {
  components: {
       VueFlux
  },
  data: () => ({
    fluxOptions: {
      autoplay: true
    },
    fluxImages: ["https://cdn-images-1.medium.com/max/1200/1*PF8Lt-1vgHeLkDstvxzhpA.jpeg",],
    fluxTransitions: {
      transitionTurn3d: Transitions.transitionTurn3d
    }
  }),
}```

**Comment by deulos** [comment]
Could you please provide a simple repo so I can so some testings?

**Comment by deulos** [comment]
I assume you already fixed the problem as not provided more info.

**Comment by LeCongThang** [comment]
@deulos Yes, i already fixed that problem. Thank you.
