### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by shirshak55** [deulos/vue-flux#21]
It shows these errors on console.

```
vue-flux.umd.min.js?fcb2:1 Uncaught TypeError: Cannot read property 'style' of undefined
    at VueComponent.nextImage (vue-flux.umd.min.js?fcb2:1)
    at VueComponent.transitionEnd (vue-flux.umd.min.js?fcb2:1)
    at eval (vue-flux.umd.min.js?fcb2:1)
```

**Comment by deulos** [comment]
That error use to be displayed when one of the images couldn't be loaded. Ensure that the images are properly set

**Comment by shirshak55** [comment]
hmm image were properly loaded slider was complaining . Currently its too weird as it is not showing any error. If it shows I will reopen. Thanks :)

**Comment by BorysTyminski** [comment]
I also had this issue when one of slider images was in assets directory.
