### ISSUE TITLE
[Question] Memory Clean up 

### ISSUE THREAD

**Issue by shirshak55** [deulos/vue-flux#24]
I use vue official router. So after navigation there are some footprints left  causing some error like

```

TypeError: Cannot read property 'style' of undefined
  at nextImage(./node_modules/vue-flux/dist/vue-flux.umd.min.js:1:67016)
  at transitionEnd(./node_modules/vue-flux/dist/vue-flux.umd.min.js:1:70339)
  at apply(./node_modules/vue-flux/dist/vue-flux.umd.min.js:1:70291)
  at wrapped(./node_modules/raven-js/src/raven.js:376:1)
```

Is there anyway to clean up memory after navigation?

**Comment by deulos** [comment]
That is probably caused by lifecycle slider not being handled properly and should not happen. Let me do some checks and I will make a new relase with this fixed this coming week.

You can use `console.clear()` to remove the console logs.

Thank you!

**Comment by shirshak55** [comment]
hmm it is not just console related things but it creates problem like with sentry. I use it so if any javascript error occurs it will report me so that i can fix things.

hmm i think this component doesn't get destroyed properly when route change

**Comment by deulos** [comment]
I have release a new version :)

Please check it and let me know.

**Comment by shirshak55** [comment]
ok if any problem i will make a new issue .
