### ISSUE TITLE
Show full image with aspect ratio

### ISSUE THREAD

**Issue by Palum12** [deulos/vue-flux#25]
Hey,
is there any way to show an image without streching it to fill the field, but with containing it with respect to its aspect ratio ? Ie. I want an vertical photo to show in its entirety with empty bars on sides and not a pixelated part of it,

**Comment by deulos** [comment]
Hello, there is no way, because doing like you say would cause the transitions to look wrong and ugly.

Sorry

**Comment by Palum12** [comment]
Ok, thank you for answer.
