### ISSUE TITLE
Ideas for new version :)

### ISSUE THREAD

**Issue by deulos** [deulos/vue-flux#27]
Hello, I'm gathering new ideas for future releases, feel free to contribute to make this component better :)

- Add image filters

**Comment by BorysTyminski** [comment]
The only thing I can think of is to somehow fix/upgrade problem with z-index of FluxIndex because now sometimes devs would need to add some additional code to fix it themselves:

![image](https://user-images.githubusercontent.com/40339232/48280325-8df71980-e453-11e8-9eb6-fe89d583dc76.png)

**Comment by deulos** [comment]
I am afraid z-index is an unavoidable situation but very easy to sort, just use from 1 to 10 to keep it in background and higher than 100 to have it in front.

In any case you still can override CSS to set its position and properties, and still is an optional component that if it dont fit your needs you can create and user your own.

Please, share an example code so I can review the complexity of the situation because maybe I am missing something or a circumstance.

Thanks mate!

**Comment by furcic** [comment]
I would like to have the option to lazy-load the images, for example to have loaded only the current image and the next/prev one or two images.

**Comment by KaiserY** [comment]
Emit some event such as ready, play, stop, end could be useful :smile:

**Comment by Peter-Krebs** [comment]
The enhancement from #35 would be very useful.

**Comment by deulos** [comment]
I will make a new year release with the ideas 😉

**Comment by deulos** [comment]
what do you think about adding a displacement filter?

https://github.com/AlbanCrepel/vue-displacement-slideshow

It looks great although would double the component size

**Comment by Peter-Krebs** [comment]
Looks very fancy, yes!
I don't mind the size too much. Would make other WebGL transitions posslble, too.

**Comment by deulos** [comment]
I have everything almost ready for the new release, although I have been struggling about how to manage the lazy-loading behavior.

The problem is that implementing it, breaks the flux-index and flux-pagination components.

The index displays thumbs of all the images so if they are not loaded I would show only the loaded ones, but that could give the impression that there are no more. Any ideas on how to circumvent this?

And for the pagination, I prepared an update that displays its thumb on mouse over, which will not be displayed. And also on clicking a pagination bullet of a non loaded image should show the spinner and wait until is loaded to display it. Is this behavior good for you or have any better idea?

Regards!

**Comment by mariusgen** [comment]
Hmm, maybe you can have them incompatible, so you will not be able to use lazy-loading with FluxIndex component. But to be honest I don't really know how everything is connected.

For my case where I need lazy-loading I forked your project and modify it for my needs, but I will be very happy to switch again to your project if there will be a lazy-load options.

Thanks for your awesome work

**Comment by deulos** [comment]
Thanks @mariusgen for your comment. I tried your fork but only displayed the first 3 images :?

I will probably end making the lazy loading to load all the images in background, not just the following 2.

It will start when 3 images are loaded, the dots of pagination with images not loaded will be disabled and the index component will display them with a grey color.

If there isn't any more comment I will implement it at the end of the week :)

Regards and thanks all!

**Comment by mariusgen** [comment]
@deulos yeah, I added a new prop 'currentIndex' for vue-flux component. I am using this prop to know which index is active and to know if I need to load new images or not. 

In my project is possible to have sliders with over a hundred images, and the user is looking only at 2 or 3 images.

**Comment by Peter-Krebs** [comment]
@deulos You requested some input regarding the flux-index and flux-pagination components.

I don't know the library a lot and I am relatively new to Vue. Just from an outside perspective:  
* I wouldn't use the library for > ~20-30 images, but it would be cool if you could.
* Lots of websites these days are driven by giving people more when they thought they're done.  
  Get to the bottom of your facebook feed - loads more stuff.  
  Scroll down on social image sharing sites - loads more stuff.  
  Keeping visitors engaged in what they're doing seems to be a good thing.
* If the slideshow is at an end - why not dynamically load a little bit more?
* Is it possible to `$emit` something for us in regards to lazy loading? Maybe a default implementation we can override?
* Is there a way to handle this gracefully by us?
  * For example using a watcher?
  * Defaulting to a placeholder image?
  * Change loading to `$emit` events with seperate implementation in case of lazy loading?

What are the things that need the implementation altered?
* Images
* Thumbnails
* Paging dots

Is it possible to let us know when these things happen so we can decide what happens and your library is the default implementation for non-lazy-loading?

**Comment by deulos** [comment]
I will implement the lazy-loading and we will evolve it ok?

I will also include some new events

**Comment by Peter-Krebs** [comment]
Sure, let's do it

**Comment by deulos** [comment]
I'm revamping VueFlux component data attributes for better understanding and I will try to make more reusable the other components so can be used for other purposes outside the slider. I will try to have it all asap :)

**Comment by bertonbeil** [comment]
Any event to detect slide change, with slide index or etc.? Please and at least one event `@change` - it will be very very useful

**Comment by deulos** [comment]
Sure, that is already implemented in the next release :)

I just had to update the architecture to make it more flexible and easier to implement the lazy loading and other features, so it is taking me more time than expected but I am on it.

**Comment by bertonbeil** [comment]
Hello, how can I detect the transition start/end?

**Comment by BorysTyminski** [comment]
@deulos `6.0.0` release will be soon? :)

**Comment by deulos** [comment]
Hey @BorysTyminski :)

I can't ensure a date, but is closer than far.

I had to rearchitect the application with controllers to manage the flow for lazy loading. Otherwise would have been a mess in the future and a nest of bugs.

I also made all the components independent, so became more like an image animation library. This also allowed to make an easier transition system when the images are replaced.

Also improved code, config and develop practices to encourage other developers to participate in the project.

My current checkpoint is the communication between components, because being independent and compatible together adds a level of complexity, and I try to keep it as easy as with the best performance. If you checkout master and try wave transition you will notice that sizes are wrong because of the communication.

Once I solve the communication just need to implement the lazy loading system and update the docs / demo.

I don't expect more than one month ;)

**Comment by BorysTyminski** [comment]
@deulos I completely understand and I'm not trying to put pressure on you. I was just curious. I'll wait patiently for next release. It's MIT project so I'm very thankful that you develop it and still working to make this app even better!

**Comment by deulos** [comment]
Hello, this week I will begin with the documentation, any desginer / volunteer?

**Comment by deulos** [comment]
6.0.0-beta.0 released just in case you want to try it...

**Comment by relief-melone** [comment]
Multiple images to be shown at once would be a great feature (similar like in vueperslides https://antoniandre.github.io/vueper-slides/?ref=madewithvuejs.com#ex--show-multiple-slides)

**Comment by deulos** [comment]
Thanks @relief-melone for the idea. The truth is that I already though about implementing it long time ago and I concluded that it is different concept, because there are no animations and most of the logic is so simple that can be achieved by using `overflow: scroll-x` CSS.

90% of animations would not be compatible nor look nice displaying more than one image at once, but if more people request it I have no problem implementing it 😄

**Comment by deulos** [comment]
I'm looking for an icon for the project, so if any of you want to contibute let me know 😄 

BTW, you can check new documentation in new [project's documentation](https://deulos.github.io/vue-flux-docs/) page.

New documentation is about 60%:
* Demos not yet implemented
* Complements are mostly updated but missing a new release
* Components are still WIP but [VueFlux](https://deulos.github.io/vue-flux-docs/documentation-6/Components/VueFlux) that is finished

Have a nice holiday!

**Comment by deulos** [comment]
If no bugs, beta.18 will be the final 6.0.0 release.

Documentation is complete without taking the demos.

If no bug found, at the end of august 6.0.0 will be released :)

**Comment by ThomasKientz** [comment]
A bit late, but for me a "hide loader" option would be great (using an empty slot atm). And also, showing 1st image while loading (so don't have a blank screen, any existing workaround ? ).

Keep up the good work, will use it in production soon ;)

**Comment by deulos** [comment]
> A bit late, but for me a "hide loader" option would be great (using an empty slot atm). And also, showing 1st image while loading (so don't have a blank screen, any existing workaround ? ).
> 
> Keep up the good work, will use it in production soon ;)

@ThomasKientz I am not sure to understand you well about "hide loader". First I would need what version are you talking about.

I will guess you speak about version 6.

If you mean that you want to display first image while loading that should be the default behavior using `FluxPreloader` component.

If you mean you do not want to display the spinner while loading just set `FluxPreloader` attribute `spinner` to `false`.

In `FluxPreloader` first image should be displayed first while loading the rest, after that, the time that takes to show next image depends on `options`, concretely `lazyLoad` and `lazyLoadAfter` options.

**Current status:**
- There is a small glitch happening when transition starts (because of browser render threads) that sometimes causes a kind of small flash and that I have currently fixed locally.
- There is also a glitch with grids having sides colored because are faster to draw than pictures so I am working on it at the moment.
- And finally I pretend to release version 6 with fixed parallax working in IOS, but if takes me more than one week I will make the release without it and add it as a fix when I find a proper way.

Thanks for the encourage 😁 

*All documentation is basically completed so if any english speaker would make me the favor to check it I would be very grateful*

[This is the documentation](https://deulos.github.io/vue-flux-docs/)
[And this the repo where you can open issues](https://github.com/deulos/vue-flux-docs)

Cheers all!!

**Comment by ThomasKientz** [comment]
@deulos 

> I will guess you speak about version 6.

I was speaking about version 5, all of my concerns are fix[ in version 6 apparently (no loader by default)](https://codesandbox.io/s/vue-flux-s0tjt), I should have tried v6 before commenting, sorry ! 

Also, a link to a [codesandbox](https://codesandbox.io/s/vue-flux-s0tjt) template would be a nice addition to the documentation :)

Nice work !

**Comment by deulos** [comment]
No problem @ThomasKientz :grin: 

I pretend to create sandboxes for all components in demos but didn't have time. Holidays in August didn't left me much time and now I am focused in v6 release, but be sure that after that, demos with source codes and sanboxes will come.

Thanks a regards!

**Comment by relief-melone** [comment]
I'd love to see types for vue-flux. I am now converting my projects over to Typescript as my experience is that in the long rund you'll always be thankful to have used ts instead of plain js. I have started working on a type-extension for v5 (which will take a while I guess) but I'm hoping this will be included in future versions of vue-flux

**Comment by deulos** [comment]
> I'd love to see types for vue-flux. I am now converting my projects over to Typescript as my experience is that in the long rund you'll always be thankful to have used ts instead of plain js. I have started working on a type-extension for v5 (which will take a while I guess) but I'm hoping this will be included in future versions of vue-flux

No doubt!

If you do it I will include it in v5, and about future versions will depend on how much does it cost to maintain.

Currently I'm refactoring the whole v6 lifecycle of the slider because of a glitch and when I finish it I will take a break for some weeks. But if anyone wants to give a hand and update the TS definitions to v6, would be great.

Thanks!

**Comment by deulos** [comment]
Hello, documentation is finished with demos and very funny playgrounds, specially in transitions 😀 

I will close this issue because it reached its purpose. If you find any bug, please open an issue.

If no bug is found, at the end of the month I will release final v6 in a week or so.

Thank you all for contributing and merry christmas!
