### ISSUE TITLE
Controls do not disappear on fullscreen

### ISSUE THREAD

**Issue by HazardDede** [deulos/vue-flux#28]
I'm not sure if this is a bug or a feature, but the controls / index do not disappear on fullscreen. Most probably this is because the pointer is always on top of the control. Is there any way to fix this? Would be nice if the controls disappear after some time and only come back when there is some movement.

**Comment by HazardDede** [comment]
Is there a quick fix that can I easily apply? 
Thanks in advance :-)

**Comment by deulos** [comment]
Sorry for the late answer.

There is no quick fix but I will create a new release within the next few days

**Comment by deulos** [comment]
Fixed in latest version :)
