### ISSUE TITLE
Mobile Gestures

### ISSUE THREAD

**Issue by HazardDede** [deulos/vue-flux#29]
Is there a way to enable mobile gestures? I can think of swipe to load the next / previous image and of pan/zoom to show the index ... The documentation states there are mobile friendly gestures but I am not able to find more documentation about this specific topic.

**Comment by deulos** [comment]
Yes, it is explained in the [VueFlux](https://github.com/deulos/vue-flux/wiki/VueFlux) component.

> In touchable screens you can slide right and left to show previous or next image. Will also display index if defined sliding up.

And in options section you will find `enableGestures`

Maybe I should create another section in wiki for it so will be easier to find the info.

**Comment by HazardDede** [comment]
XD totally missed that one. Thanks!

**Comment by deulos** [comment]
No problem, the component became so big that the documentation resulted in very long texts.

Regards!
