### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by Sushantshr** [deulos/vue-flux#3]
my main.js
`import Vue from 'vue'
import App from './App'
import router from './router'

window.Vue = require('vue')

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})`

error: 
Uncaught ReferenceError: Vue is not defined

component:
`import { VueFlux, Transitions } from 'vue-flux'
// import './node_modules/vue-flux/dist/vue-flux.css';

export default {
  components: {
    'vue-flux': VueFlux
  },

  data: () => ({
    fluxOptions: {
      autoplay: true
    },
    fluxImages: [
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random',
      'https://source.unsplash.com/random'
    ],
    fluxTransitions: {
      transitionTurn3d: Transitions.transitionTurn3d
    }
  })
}`

working in vue cli 3

**Comment by BorysTyminski** [comment]
Yes I have same error. Except that css file is missing after i run `npm install --save vue-flux`. I checked manually that there is no file named `vue-flux.css` in dist folder inside node_modules/vue-flux.

**Comment by deulos** [comment]
About the CSS you are right, since I build the code using vue-cli 3 its already included so no need to import it anymore, I will update documentation to remove that.

About Vue not being defined would help a lot if you could share a repo.

**Comment by BorysTyminski** [comment]
Error occur in google chrome console [repo demo](https://bitbucket.org/dopeCode/vue-flux-issue/src/master/).

**Comment by Sushantshr** [comment]
forget about electron just run npm install and npm run dev [repo](https://gitlab.com/sushantshr01/electron-vue)

**Comment by deulos** [comment]
Thank you, I've been checking it and seems to be some kind of problem in the last build.

Don't worry, in less than a week I'm releasing version 2 with some improvements, more configurable, parallax effect and 1 transition more.

I'll test it again with the repo you gave me.

Thank you!

**Comment by Sushantshr** [comment]
have fun coding thank you

**Comment by deulos** [comment]
Found the issue, was built as web component instead of library so as states in new vue cli 3 was only working when vue imported in html and declared as global.

Last built 2.0.3 is built as library, and is working with your repo.

Let me know if any doubt!

**Comment by BorysTyminski** [comment]
Well I changed to `"vue-flux": "^2.0.3"` in my package.json and now behaviour is that after around 5 second from page load it throw errors in console:

> [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'split' of undefined"

> found in

> ---> <TransitionTurn3d> at turn3d.vue
>       <VueFlux> at VueFlux.vue
>         <Slider> at src\components\slider.vue
>           <App> at src\App.vue
>             <Root>
> TypeError: Cannot read property 'split' of undefined

I also did push this change into [my repo demo](https://bitbucket.org/dopeCode/vue-flux-issue/src/master/).

**Comment by BorysTyminski** [comment]
I'll create another issue since I believe that it's not relevant to OP issue.
