### ISSUE TITLE
'bindKeys' option is ignored

### ISSUE THREAD

**Issue by duplo6** [deulos/vue-flux#30]
the option 'bindKeys' doesn't change anything on my page. Also fullscreen option seem always be set to 'true' (double click on the image makes it to appear as fullscreen image)

**Comment by deulos** [comment]
Thanks, I'll review it soon.

**Comment by deulos** [comment]
Hello, about the fullscreen I found the issue but couldn't find anyu problem with the bindKeys.

Can you tell me if you have the issue in the demo page too? Please give me as much info as possible like if there is any console error, browser, repo...

Thanks

**Comment by deulos** [comment]
Hello, just released a new version with the fullscreen option fixed but I was not able to reproduce the bindkeys problem.

I guess it is because of the browser. Which one do you use?

**Comment by duplo6** [comment]
Hello, thanks for the fast fix, I'm using Google Chrome for Mac, there is no error, just that the arrow keys don't appear. On the demo page everything works fine.
