### ISSUE TITLE
Sliders size not correct when hiding page at first

### ISSUE THREAD

**Issue by BorysTyminski** [deulos/vue-flux#32]
Hello so when my SPA starts I hide it for 2 seconds to show big logo gif. After 2 seconds my slider is like 100px width althought it suppose to be 100% width..

Code of my App.vue (root component) is:

```
<template>
    <div>
        <img src="../static/logo-gif.gif" alt="Active Yacht Club" class="logo">
        <div v-show="timeGap">
            <navbar></navbar>
            <transition name="zoom" mode="out-in">
                <router-view />
            </transition>
            <foot></foot>
        </div>
    </div>
</template>
```

and then in created hook im setting timeout:

       created() {
            setTimeout(() => {
                this.timeGap = true;
            },2000)
        }

and I don't know why but my slider is only 100px width.. :(

![image](https://user-images.githubusercontent.com/40339232/48867387-4b7bf800-edd6-11e8-9210-1bcffc1c55d6.png)

<hr>

When I use `v-if` directive instead of `v-show` in my root component then everything is fine but I don't really want to use v-if there as I don't want page to load only after those 2 seconds. It can be loading in background for this 2 seconds when I'm displaying logo as well.

**Comment by deulos** [comment]
That's an expected behavior.

When the slider is rendered it tries to calc its size, but as v-show keeps it hidden it has no size.

Said that, you have two options:
- After being visible, call `resize` method of the slider which will automatically detect the size.
- Set the size in options.

**Comment by deulos** [comment]
Hello mate, I close the issue as I already answered to solve it.

If you continue having trouble just let me know :)

Regards!
