### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by Rim-777** [deulos/vue-flux#33]
Hi, Your plugin looks really attractive.
 is It possible to use it  with Nuxt?

**Comment by BorysTyminski** [comment]
Check #11

**Comment by deulos** [comment]
Yes, like @BorysTyminski stated you can find some info there.

Thanks Borys!!

**Comment by deulos** [comment]
I guess that you found what you needed so I close the issue.

Shalom!

**Comment by Rim-777** [comment]
@deulos  Haven't check yet in my project, but looks Ok. Thank you!.
