### ISSUE TITLE
Gallery not clickable on some devices

### ISSUE THREAD

**Issue by HazardDede** [deulos/vue-flux#34]
On some devices (chromium on raspberry with touch screen, iPhone 7 with safari and chrome and the gestures disabled) I can open up the gallery and the items get marked when hovering over, but I can click on it like madman and nothing happens (even the gallery stays open). 

It seems to me that it has something todo with "normal" behaviour on touch devices without gestures enabled. On my raspberry the touch screen isn't detected as a touch device. On any npn-touch device it works like a charm...

Any idea?

**Comment by deulos** [comment]
Do the controls work properly on those devices?

**Comment by HazardDede** [comment]
Yes, controls work as expected

**Comment by deulos** [comment]
Great, I guess what is the problem, I will make a new release with the fix today or tomorrow top.

Thanks for reporting!

**Comment by deulos** [comment]
I released a new version and got rid of function to detect if screen is touchable, so should work on every touchable screen.

I will wait for your report :)

**Comment by HazardDede** [comment]
It just works! Nicely done!

**Comment by deulos** [comment]
Thanks! :)
