### ISSUE TITLE
Animation between changing images array

### ISSUE THREAD

**Issue by BorysTyminski** [deulos/vue-flux#35]
Well I have situation in which I have slider which fluxImages array is changing by passing props.

At first it has 3 images in array which are changing every 5 sec. After 15 sec I'm reassigning array of images to new array of 3 new images. Between array change it doesn't apply any animation but I need it to make it look cool. So is it possible? If not maybe it's good thing to add in new release?

![image](https://user-images.githubusercontent.com/40339232/49094235-0f2d1980-f266-11e8-875c-16f50ded232f.png)

This animation could be just fade or slide.

**Comment by deulos** [comment]
Currently there is no way to make it perfect. You could keep the showing image and remove the rest adding the new ones, and then after the transition of the next image ends remove the old one, but that will display 4 dots in pagination and also in the index.

I will take it in mind for the next release ;)

**Comment by deulos** [comment]
As it is done in new version I close this issue :)
