### ISSUE TITLE
Dependency error when installing with Yarn

### ISSUE THREAD

**Issue by uksitebuilder** [deulos/vue-flux#36]
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"

**Comment by deulos** [comment]
Hello, and thanks for reporting anlthough if the package corrupted is event-stream then you should open the issue to them. Unfortunally I can not do anything

**Comment by uksitebuilder** [comment]
That is a shame, I really wanted to use your gallery slider.
