### ISSUE TITLE
Technical question

### ISSUE THREAD

**Issue by rubenandrade202** [deulos/vue-flux#39]
Hi there.

I would like to know if is it possible with this project to compile it for using as single file component "web component", so that by myself define the instance of the component with html markup and Vue data object?

Thanks in advance for your work.

**Comment by deulos** [comment]
Sure!

Install vue/cli and vue/cli-service:

``` sh
npm install -g @vue/cli @vue/cli-service
```

Then clone my repo and run npm install.
``` sh
git clone https://github.com/deulos/vue-flux.git
cd vue-flux
npm install
```

And finally build it with the following command:
``` sh
vue-cli-service build --target wc --name vue-flux "src/components/index.js"
```

The webcomponent will be inside the dist folder.
