### ISSUE TITLE
flux caption

### ISSUE THREAD

**Issue by frankpet** [deulos/vue-flux#40]
Hello,

I want to have textcaptions per image .  Is it possible to get an example ( more specific ) how that has to be done.

with regards

Frank Pet

**Comment by deulos** [comment]
Hello, I updated the example in the wiki, check it out and let me know if you need a more explained example.

[FluxCaption](https://github.com/deulos/vue-flux/wiki/FluxCaption)

Regards!

**Comment by frankpet** [comment]
Hi,
Thanks for the Quick response.
I had already figured it out, but that costed some time. You're update is
much better.

By the way :  I am very satisfied with the component. Outstanding and very
easy to implement

regards
Frank

Op ma 24 dec. 2018 om 09:13 schreef Oscar <notifications@github.com>:

**Comment by deulos** [comment]
Thanks a lot for your words. Do not hesitate to contribute or ask anything you need.

Regards!
