### ISSUE TITLE
Refer Images from Assets Folder

### ISSUE THREAD

**Issue by kmshelke** [deulos/vue-flux#41]
Hi,

I need to know how to refer the images from Assets or Static folder, as this needs require function to be called in v-model and there is no provision to do so.

Thanks & Regards,

kmshelke

**Comment by deulos** [comment]
Hello, can you provide more info please?

I don't totally understand you situation.

Thanks

**Comment by SVGVR** [comment]
Hi.
I dont fully understand this question too, but if my guess is correct, then its more related to webpack.
You can read how to handle static assets in vuejs here [https://vuejs-templates.github.io/webpack/static.html](url).
Or this should help
In html
```html
<vue-flux
	:options="fluxOptions"
	:images="fluxImages"
	:transitions="fluxTransitions"
	ref="slider">
	<flux-pagination slot="pagination"></flux-pagination>
</vue-flux>
```
And in scripts something like this:
```javascript
data() {
	return {
		fluxOptions: {
			autoplay: true
		},
		fluxImages: [
			require('../assets/img/img1.jpg'),
			require('../assets/img/img2.jpg'),
		],
		fluxTransitions: {
			transitionBook: Transitions.transitionBook
		}
	}
}
```
And take a note that require('../assets/img/img1.jpg'), is a relative path.
I hope it helps.
P.s. sorry for my english, it`s not my native language

**Comment by kmshelke** [comment]
Sorry, I did not put the punctuation marks at proper place.
Thanks both of you for your response. @SVGVR, your suggestions are correct. I solved it by applying the 'require' method in the array declaration.

Thanks.

kmshelke

**Comment by deulos** [comment]
Thanks @SVGVR for clarifying.

You can also use static paths like in https://github.com/deulos/vue-flux/issues/4#issuecomment-412520024
