### ISSUE TITLE
Vue-flux in Nuxt issues (transitions and invalid array length)

### ISSUE THREAD

**Issue by BorysTyminski** [deulos/vue-flux#43]
For some reason VueFlux in Nuxt app stop working correctly when I add other component in index page In index.vue page (in pages directory) I have:

    <template>
        <div>
            <other-component></other-component>
            <VF></VF>
        </div>
    </template>

in `<VF>` component there is vueFlux component with #11 approach. 
In `<other-component>` I have:

    <template>
        <article class="bg-video">
            <app-logo></app-logo>
            <div>
                <p>Above app-logo is global component registered in global.js plugin</p>
            </div>
        </article>
    </template>

And the error is:

> TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

When I delete global component `<app-logo>` from `<other-component>` then VueFlux start working again so maybe it has something relevant to global components? I've created [depo repository](https://bitbucket.org/dopeCode/vfwithvuevideo) so you can see issue for your own.

<hr>

I dig some more and noticed that it's not the component creating error but the transitions in `default.vue` layout. Currently I don't know why yet.

<hr>

Even if I remove those transitions from default layout then after a while of vue flux playing it print error

> RangeError: Invalid array length

**Comment by deulos** [comment]
I see... I will try to create a fix today or tomorrow.

Thanks for reporting.

Regards!

**Comment by BorysTyminski** [comment]
It's weird tho because without Nuxt VueFlux was working correctly when those transitions were in App.vue. :)

**Comment by deulos** [comment]
Just remembered something, did you check #11 ?

**Comment by BorysTyminski** [comment]
Yes I'm using code from #11 and have problems because of this <transition> in default layout. I'm still fighting so maybe I'll find out.

**Comment by BorysTyminski** [comment]
Also when I have

       fluxTransitions: {
                    transitionZip: Transitions.transitionZip
        },

 I get error 

> Cannot read property 'transitionZip' of undefined

**Comment by deulos** [comment]
Hey, I am just checking it now.

I do not know if you forgot it but in the repo you gave me you are missing an important thing:

``` javascript
let VueFlux;
let Transitions;

if (process.browser) {
   const VF = require('vue-flux');
   VueFlux = VF.VueFlux;
   Transitions = VF.Transitions;
}
```

Watch the index.vue in https://github.com/deulos/vue-flux/issues/11#issuecomment-421491478

**Comment by deulos** [comment]
Forget it, just saw it in another file, do you have discord or any chat?

**Comment by deulos** [comment]
I just moved the code to `default.vue` and it works.

```javascript
    import otherComponent from '@/components/index/video/video';

    let VueFlux;
    let Transitions;

    if (process.browser) {
        const VF = require('vue-flux');
        VueFlux = VF.VueFlux;
        Transitions = VF.Transitions;
    }

    export default {
        components: {
            VueFlux,
            otherComponent
        },

        data: () => ({
            fluxOptions: {
                autoplay: true,
                delay: 5000
            },
            fluxImages: [
                'https://res.cloudinary.com/dlqvkenro/image/upload/v1542801492/7.jpg',
                'https://res.cloudinary.com/dlqvkenro/image/upload/v1542802068/3.jpg',
                'https://res.cloudinary.com/dlqvkenro/image/upload/v1542801997/6.jpg'
            ],
            fluxTransitions: Transitions
        })
    }
```

**Comment by deulos** [comment]
Just watching the error, the problem comes when trying to get the size, and because you have some transitions this could be the cause.

Did you try specifying width and height in config?

**Comment by BorysTyminski** [comment]
I had to accomplish this task ASAP so I just wrap vue-flux with `<no-ssr>` tag and it worked.
