### ISSUE TITLE
Not work with Nuxt 2.4.3

### ISSUE THREAD

**Issue by kamontat** [deulos/vue-flux#44]
The website is run and freeze.

**Comment by BorysTyminski** [comment]
> > nuxt.config.js
> 
> ```js
>   plugins: [{
>     src: '~/node_modules/vue-flux', ssr: false
>   }],
>   build: {
>     vendor : ['vue-flux'],
> ```
> 
> > index.vue
> 
> ```js
> let VueFlux;
> let Transitions;
> 
> if (process.browser) {
>    const VF = require('vue-flux');
>    VueFlux = VF.VueFlux;
>    Transitions = VF.Transitions;
> }
> 
> export default {
>    components: {
>       VueFlux
>    },
> 
>    data: () => ({
>       fluxOptions: {
>          autoplay: false
>       },
>       fluxImages: [
>          'https://source.unsplash.com/random',
>          'https://source.unsplash.com/random',
>          'https://source.unsplash.com/random'
>       ],
>       fluxTransitions: Transitions
>    })
> }
> ```

Additionally wrap component in which you have vue-flux with `<no-ssr>` tag.

**Comment by deulos** [comment]
Thanks @BorysTyminski !!

I added a section in wiki for SSR.

If everything goes well I will have the new architecture finished this weekend with the lazy loading. I would have like to finish it before but I have been pretty busy.

Regards!

**Comment by CodyBontecou** [comment]
> Thanks @BorysTyminski !!
> 
> I added a section in wiki for [SSR with Nuxt](https://github.com/deulos/vue-flux/wiki/SSR-with-Nuxt)
> 
> If everything goes well I will have the new architecture finished this weekend with the lazy loading. I would have like to finish it before but I have been pretty busy.
> 
> Regards!

It looks like the wiki link no longer works.
