### ISSUE TITLE
FluxParallax Holder not using defined element for scrolling

### ISSUE THREAD

**Issue by AMTraxTGE** [deulos/vue-flux#45]
I'm currently using FluxParallax to create sections dividing up my site. I have a custom scroll element in which the `Home.vue` view is the main scrolling element. When I pass the element through to the holder prop. I don't seem to be getting any response to the component. The object successfully passes, but the event listeners do not get applied.

`Note: I couldn't get my images to apply unless i used a require() from webpack and will create a separate issue if needed`
```html
<div class="home" ref="home">
    <Section>
        <h1>Section One</h1>
        <br v-for="i in 100" :key="i*101" />
    </Section>

    <flux-parallax :src="require('@/assets/SETUP.jpg')" height="300px" :holder="this.$refs.home" />

    <Section>
        <h1>Section Two</h1>
        <br v-for="i in 100" :key="i*101" />
    </Section>
</div>
```

Opening Chrome Dev Tools and the Vue Extension, Looking at the Props that are currently on the element and I get `holder: HTMLDivElement`. I'm not sure if that's what is suppose to be there. I know by default the Prop is set to window.

The Current Event Listeners after applying `this.$refs.home` are listed below:
![image](https://user-images.githubusercontent.com/12130422/53505957-f578b980-3a82-11e9-9640-3bafaa5ba405.png)

**Comment by deulos** [comment]
Thanks, I will review it this weekend and make a release fix

**Comment by deulos** [comment]
Sorry a lot for the dealy, this should be fixed in beta.18 which has been released now :)
