### ISSUE TITLE
captions on click or link

### ISSUE THREAD

**Issue by ab2d3e8** [deulos/vue-flux#49]
Is it possible to have caption like button click or link URL.

**Comment by deulos** [comment]
You can using your own caption component.

Take a lookt at this: https://github.com/deulos/vue-flux/wiki/Templating#caption

**Comment by ab2d3e8** [comment]
I mean that contains div a property in which elements can be added

**Comment by deulos** [comment]
You can pass any string as caption, but vue will strip out all HTML tags to prevent injection.

This is the code of the current FluxCaption component:
``` html
<div v-if="caption" class="flux-caption">{{ caption }}</div>
```

To avoid the HTML stripping you will need to create you own caption component like this:
``` html
<div v-if="caption" v-html="caption" class="flux-caption"></div>
```

**Comment by ab2d3e8** [comment]
Thanks
