### ISSUE TITLE
Example from Installation Guide - VueFlux, Pagination and Transitions all are undefined

### ISSUE THREAD

**Issue by relief-melone** [deulos/vue-flux#50]
Hey guys,

I feel kind of stupid if this is not an issue but I've been trying around for quite a while now and I don't get the example from the installtion guide to run and also the wiki couldnt help me. 

Console will always throw 

> Error in data(): "TypeError: Cannot read property 'transitionBook' of undefined"

so I add a 

```javascript
console.log(Transitions);
```

and it returns undefined. That made me curious and VueFlux and FluxPagination also return undefined. Am I completely wrong here or is there a bug with the latest relase?

Versions:

**vue-flux:** 6.0.0-beta.0
**vue:** 3.7.0

**Comment by deulos** [comment]
Hello! sorry for the inconvenience but just released version 6 yesterday and documentation is not updated yet.

Please use version 5.X

**Comment by deulos** [comment]
I added the tag beta to the package so that version should not be instanlled by default 😄

**Comment by relief-melone** [comment]
Yes. I wanted to look if I'm right and downgraded. And see it works. I guess I'll close that. One totally unrelated question I might ask. Do you have any example where you set up vue-flux with the interface (arrows and gallery button)

Thanks for the quick reply. Not in there very deep but already the nicest image slider/gallery I've come across yet for vue

**Comment by deulos** [comment]
I think the readme had the example with the interface, but it is as easy as placing those components inside the vue-flux component and referencing the slot.

thanks for your words!
cheera
