### ISSUE TITLE
currentCaption - can't find it

### ISSUE THREAD

**Issue by mime55** [deulos/vue-flux#51]
Hi!
First off - great component!

I have an issue with the captions. I want to put links on them and have created a custom caption. I saw `$refs.slider.currentCaption` mentioned in another issue, but it doesn't seem to work anymore.

Can you point me in the right direction here?

Thanks

**Comment by deulos** [comment]
Which version are you using?

If you are trying the 6-beta.0 version that method is not available anymore as I moved and splitted most of the code. Now this would be the way:

``` javascript
let currentImage = $refs.slider.Images.current;
let caption = $refs.slider.captions[currentImage.index];
```

And now that I see it, does not look very practical... I will add an easy way to get the current caption and also allow to pass an HTML template to the component so can me more customizable.

**Comment by mime55** [comment]
Ok. I am using version 5.1.9. But I can still not get anything from `$refs.slider.currentCaption`. Am I supposed to?

**Comment by deulos** [comment]
Just checked it and that property is not available in the slider because the logic was moved to the FluxCaption component.

But because you are not using that component, you cant get the image index currently displayed with `$refs.slider.currentImage().index` and show corresponding caption of your captions array.

**Comment by deulos** [comment]
As now news, I understand that your needs were solved.

Also new version is fully themable by using the [caption slot](https://deulos.github.io/vue-flux-docs/documentation-6/Templating.html#caption).

If previous URL fails (will be removed soon) check [FluxCaption](https://deulos.github.io/vue-flux-docs/documentation-6/Components/Complements/FluxCaption) component documentation.
