### ISSUE TITLE
'naturalWidth' of undefined

### ISSUE THREAD

**Issue by dukecan123** [deulos/vue-flux#52]
Component not loaded, switch page appears "'naturalWidth' of undefined".

**Comment by deulos** [comment]
which version are you using?

**Comment by kunbimajek** [comment]
Im getting a similar error a few minutes after it runs.
" Cannot read property 'width' of undefined "

please help

**Comment by deulos** [comment]
Hello, that use to happen when the image is not found, maybe wrong name or path.

check the dev tools network tab to identify which one.

regards

**Comment by zSakuraEvilz** [comment]
I also get the error "Cannot read property 'width' of undefined"
Error encountered when changing the browser size that the slider is running.
Or when viewing the full screen image and exit that slider is running.
[https://uphinh.org/image/MkE4xT](url)

**Comment by zSakuraEvilz** [comment]
I investigated the error as a result of FluxTransition.
At funtion style in the computed section.
this.size undefined

**Comment by deulos** [comment]
Thanks, I will review it and make a new release in the next days.

Regards!

**Comment by deulos** [comment]
New release ready :)

Now on resizing, if there is a transition running will cancel it.
