### ISSUE TITLE
Set transitions through props

### ISSUE THREAD

**Issue by shubhra14** [deulos/vue-flux#54]
Hi,

Is there a way I can set transition type through props. I have made a custom component with vue-flux and want to use the slider in different places but with different transitions.
I want to be able to do this:
```
<slider transition="Kenburn"></slider>
<slider transition="Book"></slider>
```
If I do:
```
transition: {
      type: String,
      required: false,
      default: 'Swipe'
    },
```
How can I use it here?:
```
fluxTransitions: {
         transitionKenburn: Transitions.transitionKenburn
      }
```

Also, If I dont define height anywhere, the slider doesn't show because of height 100%. How are you doing it in the demo page? I would like to avoid giving it a height at every breakpoint.

**Comment by deulos** [comment]
Hello, for the first question you have 2 choices.

The easiest is to use the next version which only receives an [array of strings](https://deulos.github.io/vue-flux-docs/v6/components/vue-flux.html#transitions), this version is pretty stable already and I'm not supposed to change any option or parameter.

The other way is to make your component transform that string into transition component and include it. If you don't know how, you can check how I did it in the new [FluxTransition](https://github.com/deulos/vue-flux/blob/dev/src/components/FluxTransition.vue) that created in the next version.

About the height, if you are using 5.1.9, it is determined by the CSS or style defined, but if it is not defined, the slider will calculate the height using a 16:9 ratio. In case you are using previous versions the size is also taken from the parent, so you may have the parent with a 100% height.

**Comment by shubhra14** [comment]
Both the things were resolved with the new version. 
`vfTransitions: [ this.transition ]` works and I don't have to define height. It works as is.
Amazing! Thank you!
