### ISSUE TITLE
vue-flux/complements dependency was not found

### ISSUE THREAD

**Issue by cartoonmadrasah** [deulos/vue-flux#57]
I am trying to install the latest beta of vue-flux and it is throwing this error. What to do?

This dependency was not found:

* vue-flux/complements in ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue-flux/complements

**Comment by deulos** [comment]
You can not install complements independently, and they are already included in the 
[components](https://github.com/deulos/vue-flux/blob/dev/src/components/index.js)

**Comment by cartoonmadrasah** [comment]
No I had installed using the command: npm install --save vue-flux@beta

There was no components folder in the node_modules/vue-flux

**Comment by deulos** [comment]
Sorry but I just did a try and everything worked properly:

![image](https://user-images.githubusercontent.com/6222619/63030946-8289c080-beb3-11e9-8477-bfeb007f145a.png)

Try to delete the folder from node_modules and install it again. If it still cause you a problem try to run it with `--loglevel verbose` so maybe there is a useful info t osolve the problem
