### ISSUE TITLE
"Direction" option ignored (V5)

### ISSUE THREAD

**Issue by gterras** [deulos/vue-flux#59]
Hi, 

Thanks for your super nice plugin. I noticed the `direction` option is ignored whatever I try to set it (as a component prop, in the `options` object, `transitionOptions` object or by setting it directly with `ref`). Is this a read only option ? 

My goal is just to have a slider that always transition in the same direction (what most sliders call `infinite`). I've read that you have removed this option from V6, is there any kind of replacement ? Thanks

**Comment by deulos** [comment]
Hello, and thank for your words :grin: 

The `direction` options was indeed removed from transition options and was used for example to allow run a transition fade in or fade out, but that direction did not affect the order the images are displayed, nor if it stops when reached last image :smile: 

Currently all transitions have a single direction and run infinitely unless you set [infinite option](https://deulos.github.io/vue-flux-docs/v6/components/vue-flux.html#options) to `false`

**Comment by gterras** [comment]
Thanks for your answer mate. 

> Currently all transitions have a single direction and run infinitely

Are you talking about v6 ? Because v5 does this weird thing where the first slide is called again with a reversed transition. If yes do you consider it usable in a production environment despite the beta flag ?

**Comment by deulos** [comment]
Yes, I speak about v6, when reaching last image will start from the beginning without using the transition reversed.

The only 2 reasons for not releasing v6 are the following:
- In unreleased beta, and in my computer, using firefox I can is a glitch when transition starts, not very noticeable but I want know where does it comes.
- I am trying to find a fix for fixed parallax in ios (this one may not be in the release)

**Comment by gterras** [comment]
Thanks for the info, I tried this and this works perfectly. Maybe I can try to help for the Firefox glitch if you have a reproducible setup somewhere (I've tried many transitions and did not observe any glitch). 

By the way the v6 README has an incorrect import example (no destructuring for VueFlux import and wrong source for side components import), the v6 doc page is right about that.

**Comment by deulos** [comment]
Thanks a lot for reporting the README, I will fix it today :grin:
