### ISSUE TITLE
Bind html to captions

### ISSUE THREAD

**Issue by d0peCode** [deulos/vue-flux#6]
Hello I have captions option enabled on vue-flux component and I want to bind h3 tag into caption I tried like so

        <vue-flux
            :options="fluxOptions"
            :images="fluxImages"
            :transitions="fluxTransitions"
            :captions="fluxCaptions"
            ref="slider">
        </vue-flux>

    export default {
        components: {
            'vue-flux': VueFlux,
            'vue-index': FluxIndex,
            'flux-image': FluxImage
        },
        data: () => ({
            fluxOptions: {
                autoplay: true,
                delay: 7000,
            },
            fluxImages: [
                'static/1.jpg',
                'static/2.jpg',
                'static/3.jpeg'
            ],
            fluxTransitions: {
                transitionBars2d: Transitions.transitionBars2d,
                transitionBlocks2d1: Transitions.transitionBlocks2d1,
                transitionSlide2d: Transitions.transitionSlide2d
            },
            fluxCaptions: ['<h3>aa</h3>', 'bb', 'cc']
        })
    }

but it actually print only string into caption. How to bind html there?

**Comment by deulos** [comment]
Not possible right now as it interpolates removing tags for security risks...

Do you really need add tags?

**Comment by BorysTyminski** [comment]
What I want to achieve is changing header on slider. I override `.caption` css and I made it look how I want but the last thing was to put `<h2>` tag inside my caption. Since I'm already using this component I would like to use captions because they nicely show and hide during animation.

I probably could also put entire slider into relative position div and display my own captions on animations finish but I would need access to event on animation start, event on animation end and info which image is currently displayed. I don't really see info in wiki's about it :(.

**Comment by deulos** [comment]
I'll take captions apart like the other components with slot so you can customize everything as you need.

Right now I'm not firing events but will take it in mind.

Sorry that I forgot to update the wiki with the new properties, i didt it right now.

You can get current image index of the array with:
``` javascript
$refs.slider.currentImage.index;
```
Or you can use the new property:
``` javascript
$refs.slider.currentCaption
```
It will return the caption text when current image has it and not transition in course or empty string. Anyway as I'm taking captions apart this will be moved also to the new component and you can create your own and customize at max.

What I currently do is:
``` html
<div class="caption" :class="currentCaption? 'display' : ''">{{ currentCaption }}</div>
```
``` css
.caption {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    padding: 8px;
    color: white;
    text-align: center;
    background-color: rgba(0, 0, 0, 0.65);
    opacity: 0;
    transition: opacity 0.3s ease-in;
    z-index: 100;
}

.caption.display {
    opacity: 1;
}
```
