### ISSUE TITLE
Destroy The Slider After Component Destruction

### ISSUE THREAD

**Issue by alfavat** [deulos/vue-flux#62]

**Comment by deulos** [comment]
Can you give more details?

Why do you think the slider is not destroyed?

Just did a simple test with a checkbox and `v-if` in the slider and even in the middle a of a transitions the component dissapeared

**Comment by alfavat** [comment]
Sorry I just pressed Enter and i  did not have chance to write more details
actually i thought  there might be a special method that i should call
i did not test if it destroys itself
right now before your answer i was checking it in chrome 
and it seems that you are right i was not able to find memory leak
thank you for quick response

**Comment by deulos** [comment]
No worries!

Regards
