### ISSUE TITLE
How hide play/pause buttom?

### ISSUE THREAD

**Issue by kaiunido** [deulos/vue-flux#66]
Hi, there's a way to hide/remove from controls the play/pause button?

Thanks.

**Comment by deulos** [comment]
Hello, you can set the class `flux-controls.play flux-controls.stop` to display none

Regards!

**Comment by kaiunido** [comment]
@deulos thanks, i did it after asking this question yesterday. I asked because I thought there was some other way. But thanks a lot. ^^

`.flux-controls {
   .play, .pause {
     display: none !important;
   }
 }`
