### ISSUE TITLE
Ratio

### ISSUE THREAD

**Issue by univers-graphik** [deulos/vue-flux#70]
Hi. It's possible to change default ratio 16:9 ?
I don't wank fix height with css for keep responsive.
Thanks

**Comment by deulos** [comment]
Hello, you can define the size you want by CSS.

Take a look at https://deulos.github.io/vue-flux-docs/v6/components/vue-flux.html#size

**Comment by deulos** [comment]
Re-reading your question again, I think that I misunderstood what you were trying to achieve.

If you want to keep it responsive, but with a different aspect ratio, I think there is a CSS trick. Anyway is a good feature to add 😁 

I will try to make a new release this week with it.

Thanks!

**Comment by univers-graphik** [comment]
Thanks for your fast response. 
I know another good lib who use same you the background image and ratio.
This lib propose a props for the ratio, it's a good idea.

**Comment by univers-graphik** [comment]
I have just a second question about lazy (default true)
When my page is loaded, in my console all images are loaded. (normally just the first no ?)
After when i use (next prev), effectively just the request for the next image is launch.

Thanks and good job ;)

**Comment by deulos** [comment]
I already published the new version 6.1.1 which includes the option for aspet ratio :grinning: 

Just add the corresponding option as:
``` js
aspectRatio: '16:9'
```

I also added the option to the documentation. Feel free to let me know if you have any doubt.

Regards!

**Comment by malbrock** [comment]
Hi Ragnarlotus! I really appreciate your work on this component. Just one comment on the aspectRatio, is that it seems that it doesn't affect the thumbnails on the Index. Is it possible to affect the thumbnails as well? Thanks in advance!

**Comment by ragnarlotus** [comment]
Hello, @malbrock and thanks for your kind words!

Please open an issue for that and I will try to release an update with it this weekend 😉 

Regards
