### ISSUE TITLE
How to insert picture from assets directorium in Vue?

### ISSUE THREAD

**Issue by kirk7183** [deulos/vue-flux#76]
i tryed like this but pictures do not show 

  vfImages: [
        "@/assets/slika-3.jpg",
        "@/assets/slika-2.jpg",
        "@/assets/slika-12.jpg"
      ],

**Comment by deulos** [comment]
Hello, I don't recommend using the assets folder for images, but you can get how from #72 

Regards!

**Comment by kirk7183** [comment]
It work, but now i found new big issue.... if i have menu over picture...the place where picture is under menu i can not click on it...because it recognize click on picture look... 
![image](https://user-images.githubusercontent.com/58073480/88058031-359e7780-cb63-11ea-8cd6-b400400de819.png)

i can click on "Cenovnik" and "O nama" ...but cannot click or other 2 that i selected with red color...if i remove flux ..it works OK

**Comment by deulos** [comment]
Don't worry, that's not a big issue :)

You just have a CSS positioning problem. Just give the menu a `z-index` over 100 and probably will be enough, guessing the menu `position` is `absolute`.

Regards

**Comment by kirk7183** [comment]
Working ! Ty a lot 👍

**Comment by deulos** [comment]
No problem :)
