### ISSUE TITLE
Duration of slide? Am I missing it in docs?

### ISSUE THREAD

**Issue by midlantica** [deulos/vue-flux#77]
Great carousel, thanks.. can't find duration.. 

(tried to delete this but it won't let me)

**Comment by midlantica** [comment]
Ahh! https://deulos.github.io/vue-flux-docs/v5/components/vue-flux.html#options

**Comment by deulos** [comment]
Notice that the URL you linked is the v5 of the component and you are probably using v6.

Thanks for your compliments :)

Regards!

**Comment by deulos** [comment]
And no worries about deleting, this is also a source of info for many people, so it is ok ;P
