### ISSUE TITLE
Slider blocks actions on the whole page when in hover mode

### ISSUE THREAD

**Issue by calpayne** [deulos/vue-flux#79]
When you hover over a slider, if you move your cursor off to the left or right, the hover mode disables. But if you move your cursor off to the top, the hover mode stays active and blocks any actions anywhere else on the page.

I figured maybe my setup was causing it but this bug is also on the demo,
https://gyazo.com/82403bac35566dd70db6830b9526ce25

**Comment by calpayne** [comment]
Putting the slider into the FluxWrapper has fixed this issue

**Comment by deulos** [comment]
Thanks a lot for reporting, It shouldn't happen.

I will check it and let you know :)

**Comment by deulos** [comment]
Fixed
