### ISSUE TITLE
How would i set the height conditionally?

### ISSUE THREAD

**Issue by micos7** [deulos/vue-flux#83]
I have a series of vertical divs in a loop with vue-flux in each. The problem is that the height is constant even if that particular div has no images. How would I set the height conditionally so height is 0 when there are no images? Thanks for your time.

![Screenshot from 2020-08-04 17-56-00](https://user-images.githubusercontent.com/4460809/89309230-d3259b00-d67b-11ea-8d63-6ebb175eccda.png)

**Comment by deulos** [comment]
Hello, the size of the slider is calculated based in the parent when rendered, and is not recalculated if the windows is not resized. But you can call [resize](https://deulos.github.io/vue-flux-docs/v6/components/vue-flux.html#resize) to force it to resize.

Let me know that works for you.

Regards!

**Comment by micos7** [comment]
Thanks for answering.Resize didn`t do anything in my situation so I used a v-if to only show the component if there are images.

**Comment by deulos** [comment]
Oh, I think I missunderstood your question but I'm glad to see that you already achieved what you wanted.

Regards!
