### ISSUE TITLE
Having a trouble loading an image in 'flux-parallax' component

### ISSUE THREAD

**Issue by bcchoir1954dev** [deulos/vue-flux#84]
my folder structure

> src
> - assets
>   - images
>     - sample.png
> - views
>   - Home.vue

and in Home.vue
```
<flux-parallax
     src="../assets/images/sample.png"
     style="height: 600px;"
     type="fixed"
></flux-parallax>
```

In the developer console, it says

> Image ../assets/images/sample.png could not be loaded

I'm very new to VueJS and would like to know how to use this correctly.

**Comment by deulos** [comment]
Hello, use the public folder instead.

Chevk #72 for further info.

Regards!

**Comment by bcchoir1954dev** [comment]
I've tried it and it works now. Thank you so much.

Regards!

**Comment by bcchoir1954dev** [comment]
I have another problem. 
```
<flux-parallax
  src="/img/sample.jpg"
  style="height: 600px; filter: blur(2px) contrast(0.5);"
  type="fixed"
></flux-parallax>
```
When I write code as above, the result looks weird
![parallax_fixed](https://user-images.githubusercontent.com/70301435/92320416-99193180-f04b-11ea-8f6b-85b6114b6241.png)
Could you please figure it out for me.

Regards

**Comment by deulos** [comment]
Hello, could you prepare a sandbox where I can understand better what you are trying to achieve? I'm not sure what is what you really want to do.

Regards

**Comment by bcchoir1954dev** [comment]
Hello,
Maybe this gif makes you understand the problem.
![parallax_example_gif](https://user-images.githubusercontent.com/70301435/92631401-80cf3e00-f2fb-11ea-9993-f8504076c9f3.gif)

This is the image I used
![cat](https://user-images.githubusercontent.com/70301435/92631625-ce4bab00-f2fb-11ea-9359-4a6e87dd4fa9.jpg)

I don't know whether I have done something wrong or not. 

This is the code I wrote
Parallax.vue : https://pastebin.pl/view/57888bf5
ParallaxContent.vue : https://pastebin.pl/view/cb801597

Regards,
Peachy

**Comment by deulos** [comment]
Thanks a lot for taking some time to give me the example codes. I did a review and certainly there is a bug with images smaller than the component size.

I will release the fix within the next days

Thanks!

**Comment by deulos** [comment]
I just released a new version with the fix.

Let me know if any problem.

Thanks!
