### ISSUE TITLE
How to add img url for images from assets folder

### ISSUE THREAD

**Issue by gribchic** [deulos/vue-flux#88]
I've tried to add images in different ways 
` vfImages: [ 'assets/slide-finance-1.jpg', '../../assets/slide-finance-2.jpg' , '@/assets/slide-finance-2.jpg'],`
but i have the same error:
`Image assets/slide-finance-1.jpg could not be loaded
or
Image ../../assets/slide-finance-2.jpg could not be loaded
or
Image @/assets/slide-finance-2.jpg could not be loaded
`

**Comment by deulos** [comment]
Please, check the closed issues, there are enough info there.


Regards
