### ISSUE TITLE
stop looping

### ISSUE THREAD

**Issue by almas-alright** [deulos/vue-flux#89]
is there any way to stop loop or detect last slide? if anyone want to see any previous slide she may go with previous/next. i am showing some instructions (work safety guideline) through this nice slider after last slide i want to stop it and move user to a different page (question page).

**Comment by deulos** [comment]
Hello, check [Options](https://deulos.github.io/vue-flux-docs/v6/components/vue-flux.html#options) and look at `infinite`

Then check [Events](https://deulos.github.io/vue-flux-docs/v6/components/vue-flux.html#events) and look at `stop` to know when to redirect to another page :)

Regards!
