### ISSUE TITLE
Flux caption typo Error

### ISSUE THREAD

**Issue by mpwanyi256** [deulos/vue-flux#90]
##I believe the sentence was supposed to be `It is a default component to display image caption.`

![typo](https://user-images.githubusercontent.com/20843520/97455192-a61a1900-1948-11eb-978f-0dc19f3bcebd.png)

**Comment by deulos** [comment]
Yes thank you!, I will update it asap.

Regards!

**Comment by mpwanyi256** [comment]
cheers

**Comment by mpwanyi256** [comment]
Cheers, thanks

Regards Mpwanyi Samuel

+256706523078
+256780101601
